version: 2.1
jobs:
  test:
    docker:
      - image: circleci/python:3.7.7
    steps:
      - checkout
  build:
    machine:
      image: circleci/python:3.7.7
      docker_layer_caching: true
    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:
          docker_layer_caching: true

      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t $DOCKER_USER/${CIRCLE_PROJECT_REPONAME}:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push DOCKER_USER/${CIRCLE_PROJECT_REPONAME}:$TAG